// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: worker.proto

package worker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerManagement_RegisterWorker_FullMethodName  = "/payflow.worker.v1.WorkerManagement/RegisterWorker"
	WorkerManagement_Heartbeat_FullMethodName       = "/payflow.worker.v1.WorkerManagement/Heartbeat"
	WorkerManagement_PollTasks_FullMethodName       = "/payflow.worker.v1.WorkerManagement/PollTasks"
	WorkerManagement_ReportResult_FullMethodName    = "/payflow.worker.v1.WorkerManagement/ReportResult"
	WorkerManagement_RevokeTask_FullMethodName      = "/payflow.worker.v1.WorkerManagement/RevokeTask"
	WorkerManagement_WorkerHeartbeat_FullMethodName = "/payflow.worker.v1.WorkerManagement/WorkerHeartbeat"
)

// WorkerManagementClient is the client API for WorkerManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerManagementClient interface {
	RegisterWorker(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	PollTasks(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskAssignment], error)
	ReportResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*ResultAck, error)
	RevokeTask(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeAck, error)
	WorkerHeartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatPing, HeartbeatAck], error)
}

type workerManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerManagementClient(cc grpc.ClientConnInterface) WorkerManagementClient {
	return &workerManagementClient{cc}
}

func (c *workerManagementClient) RegisterWorker(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, WorkerManagement_RegisterWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerManagementClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, WorkerManagement_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerManagementClient) PollTasks(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskAssignment], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerManagement_ServiceDesc.Streams[0], WorkerManagement_PollTasks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PollRequest, TaskAssignment]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerManagement_PollTasksClient = grpc.ServerStreamingClient[TaskAssignment]

func (c *workerManagementClient) ReportResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*ResultAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResultAck)
	err := c.cc.Invoke(ctx, WorkerManagement_ReportResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerManagementClient) RevokeTask(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeAck)
	err := c.cc.Invoke(ctx, WorkerManagement_RevokeTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerManagementClient) WorkerHeartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatPing, HeartbeatAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerManagement_ServiceDesc.Streams[1], WorkerManagement_WorkerHeartbeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeartbeatPing, HeartbeatAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerManagement_WorkerHeartbeatClient = grpc.BidiStreamingClient[HeartbeatPing, HeartbeatAck]

// WorkerManagementServer is the server API for WorkerManagement service.
// All implementations must embed UnimplementedWorkerManagementServer
// for forward compatibility.
type WorkerManagementServer interface {
	RegisterWorker(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	PollTasks(*PollRequest, grpc.ServerStreamingServer[TaskAssignment]) error
	ReportResult(context.Context, *TaskResult) (*ResultAck, error)
	RevokeTask(context.Context, *RevokeRequest) (*RevokeAck, error)
	WorkerHeartbeat(grpc.BidiStreamingServer[HeartbeatPing, HeartbeatAck]) error
	mustEmbedUnimplementedWorkerManagementServer()
}

// UnimplementedWorkerManagementServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerManagementServer struct{}

func (UnimplementedWorkerManagementServer) RegisterWorker(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterWorker not implemented")
}
func (UnimplementedWorkerManagementServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedWorkerManagementServer) PollTasks(*PollRequest, grpc.ServerStreamingServer[TaskAssignment]) error {
	return status.Error(codes.Unimplemented, "method PollTasks not implemented")
}
func (UnimplementedWorkerManagementServer) ReportResult(context.Context, *TaskResult) (*ResultAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportResult not implemented")
}
func (UnimplementedWorkerManagementServer) RevokeTask(context.Context, *RevokeRequest) (*RevokeAck, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeTask not implemented")
}
func (UnimplementedWorkerManagementServer) WorkerHeartbeat(grpc.BidiStreamingServer[HeartbeatPing, HeartbeatAck]) error {
	return status.Error(codes.Unimplemented, "method WorkerHeartbeat not implemented")
}
func (UnimplementedWorkerManagementServer) mustEmbedUnimplementedWorkerManagementServer() {}
func (UnimplementedWorkerManagementServer) testEmbeddedByValue()                          {}

// UnsafeWorkerManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerManagementServer will
// result in compilation errors.
type UnsafeWorkerManagementServer interface {
	mustEmbedUnimplementedWorkerManagementServer()
}

func RegisterWorkerManagementServer(s grpc.ServiceRegistrar, srv WorkerManagementServer) {
	// If the following call panics, it indicates UnimplementedWorkerManagementServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerManagement_ServiceDesc, srv)
}

func _WorkerManagement_RegisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerManagementServer).RegisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerManagement_RegisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerManagementServer).RegisterWorker(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerManagement_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerManagementServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerManagement_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerManagementServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerManagement_PollTasks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PollRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerManagementServer).PollTasks(m, &grpc.GenericServerStream[PollRequest, TaskAssignment]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerManagement_PollTasksServer = grpc.ServerStreamingServer[TaskAssignment]

func _WorkerManagement_ReportResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerManagementServer).ReportResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerManagement_ReportResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerManagementServer).ReportResult(ctx, req.(*TaskResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerManagement_RevokeTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerManagementServer).RevokeTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerManagement_RevokeTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerManagementServer).RevokeTask(ctx, req.(*RevokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerManagement_WorkerHeartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerManagementServer).WorkerHeartbeat(&grpc.GenericServerStream[HeartbeatPing, HeartbeatAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerManagement_WorkerHeartbeatServer = grpc.BidiStreamingServer[HeartbeatPing, HeartbeatAck]

// WorkerManagement_ServiceDesc is the grpc.ServiceDesc for WorkerManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payflow.worker.v1.WorkerManagement",
	HandlerType: (*WorkerManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWorker",
			Handler:    _WorkerManagement_RegisterWorker_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _WorkerManagement_Heartbeat_Handler,
		},
		{
			MethodName: "ReportResult",
			Handler:    _WorkerManagement_ReportResult_Handler,
		},
		{
			MethodName: "RevokeTask",
			Handler:    _WorkerManagement_RevokeTask_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PollTasks",
			Handler:       _WorkerManagement_PollTasks_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WorkerHeartbeat",
			Handler:       _WorkerManagement_WorkerHeartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "worker.proto",
}
