// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: worker.proto

package worker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Epoch              int64                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	WorkerId           string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ProcessingCapacity int32                  `protobuf:"varint,3,opt,name=processing_capacity,json=processingCapacity,proto3" json:"processing_capacity,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *RegisterRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterRequest) GetProcessingCapacity() int32 {
	if x != nil {
		return x.ProcessingCapacity
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HeartbeatRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Epoch               int64                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	WorkerId            string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CurrentLoad         int32                  `protobuf:"varint,3,opt,name=current_load,json=currentLoad,proto3" json:"current_load,omitempty"`
	TasksProcessedCount int32                  `protobuf:"varint,4,opt,name=tasks_processed_count,json=tasksProcessedCount,proto3" json:"tasks_processed_count,omitempty"`
	AvgTaskDurationMs   int32                  `protobuf:"varint,5,opt,name=avg_task_duration_ms,json=avgTaskDurationMs,proto3" json:"avg_task_duration_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetCurrentLoad() int32 {
	if x != nil {
		return x.CurrentLoad
	}
	return 0
}

func (x *HeartbeatRequest) GetTasksProcessedCount() int32 {
	if x != nil {
		return x.TasksProcessedCount
	}
	return 0
}

func (x *HeartbeatRequest) GetAvgTaskDurationMs() int32 {
	if x != nil {
		return x.AvgTaskDurationMs
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type PollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollRequest) Reset() {
	*x = PollRequest{}
	mi := &file_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRequest) ProtoMessage() {}

func (x *PollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRequest.ProtoReflect.Descriptor instead.
func (*PollRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{4}
}

func (x *PollRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type TaskAssignment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Epoch          int64                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	TaskId         string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Amount         float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency       string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	MerchantId     string                 `protobuf:"bytes,6,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{5}
}

func (x *TaskAssignment) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *TaskAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAssignment) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *TaskAssignment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TaskAssignment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TaskAssignment) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type TaskResult struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Epoch    int64                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	TaskId   string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Types that are valid to be assigned to Status:
	//
	//	*TaskResult_Success
	//	*TaskResult_ErrorMessage
	Status        isTaskResult_Status `protobuf_oneof:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{6}
}

func (x *TaskResult) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskResult) GetStatus() isTaskResult_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *TaskResult) GetSuccess() bool {
	if x != nil {
		if x, ok := x.Status.(*TaskResult_Success); ok {
			return x.Success
		}
	}
	return false
}

func (x *TaskResult) GetErrorMessage() string {
	if x != nil {
		if x, ok := x.Status.(*TaskResult_ErrorMessage); ok {
			return x.ErrorMessage
		}
	}
	return ""
}

type isTaskResult_Status interface {
	isTaskResult_Status()
}

type TaskResult_Success struct {
	Success bool `protobuf:"varint,4,opt,name=success,proto3,oneof"`
}

type TaskResult_ErrorMessage struct {
	ErrorMessage string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3,oneof"`
}

func (*TaskResult_Success) isTaskResult_Status() {}

func (*TaskResult_ErrorMessage) isTaskResult_Status() {}

type ResultAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultAck) Reset() {
	*x = ResultAck{}
	mi := &file_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultAck) ProtoMessage() {}

func (x *ResultAck) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultAck.ProtoReflect.Descriptor instead.
func (*ResultAck) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{7}
}

func (x *ResultAck) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type RevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	mi := &file_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{8}
}

func (x *RevokeRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type RevokeAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAck) Reset() {
	*x = RevokeAck{}
	mi := &file_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAck) ProtoMessage() {}

func (x *RevokeAck) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAck.ProtoReflect.Descriptor instead.
func (*RevokeAck) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{9}
}

func (x *RevokeAck) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type HeartbeatPing struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	WorkerId            string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Load                float32                `protobuf:"fixed32,2,opt,name=load,proto3" json:"load,omitempty"` // active_tasks / max_capacity, 0.0-1.0
	TasksProcessedCount int64                  `protobuf:"varint,3,opt,name=tasks_processed_count,json=tasksProcessedCount,proto3" json:"tasks_processed_count,omitempty"`
	AvgTaskDurationMs   int64                  `protobuf:"varint,4,opt,name=avg_task_duration_ms,json=avgTaskDurationMs,proto3" json:"avg_task_duration_ms,omitempty"`
	Epoch               int64                  `protobuf:"varint,5,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HeartbeatPing) Reset() {
	*x = HeartbeatPing{}
	mi := &file_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPing) ProtoMessage() {}

func (x *HeartbeatPing) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPing.ProtoReflect.Descriptor instead.
func (*HeartbeatPing) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatPing) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatPing) GetLoad() float32 {
	if x != nil {
		return x.Load
	}
	return 0
}

func (x *HeartbeatPing) GetTasksProcessedCount() int64 {
	if x != nil {
		return x.TasksProcessedCount
	}
	return 0
}

func (x *HeartbeatPing) GetAvgTaskDurationMs() int64 {
	if x != nil {
		return x.AvgTaskDurationMs
	}
	return 0
}

func (x *HeartbeatPing) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         int64                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{11}
}

func (x *HeartbeatAck) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

var File_worker_proto protoreflect.FileDescriptor

const file_worker_proto_rawDesc = "" +
	"\n" +
	"\fworker.proto\x12\x11payflow.worker.v1\"{\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12/\n" +
	"\x13processing_capacity\x18\x03 \x01(\x05R\x12processingCapacityJ\x04\b\x04\x10\v\",\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xcd\x01\n" +
	"\x10HeartbeatRequest\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12!\n" +
	"\fcurrent_load\x18\x03 \x01(\x05R\vcurrentLoad\x122\n" +
	"\x15tasks_processed_count\x18\x04 \x01(\x05R\x13tasksProcessedCount\x12/\n" +
	"\x14avg_task_duration_ms\x18\x05 \x01(\x05R\x11avgTaskDurationMs\"7\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"*\n" +
	"\vPollRequest\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\"\xbd\x01\n" +
	"\x0eTaskAssignment\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1f\n" +
	"\vmerchant_id\x18\x06 \x01(\tR\n" +
	"merchantId\"\xa5\x01\n" +
	"\n" +
	"TaskResult\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12\x1a\n" +
	"\asuccess\x18\x04 \x01(\bH\x00R\asuccess\x12%\n" +
	"\rerror_message\x18\x05 \x01(\tH\x00R\ferrorMessageB\b\n" +
	"\x06status\"/\n" +
	"\tResultAck\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"(\n" +
	"\rRevokeRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"/\n" +
	"\tRevokeAck\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"\xbb\x01\n" +
	"\rHeartbeatPing\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x12\n" +
	"\x04load\x18\x02 \x01(\x02R\x04load\x122\n" +
	"\x15tasks_processed_count\x18\x03 \x01(\x03R\x13tasksProcessedCount\x12/\n" +
	"\x14avg_task_duration_ms\x18\x04 \x01(\x03R\x11avgTaskDurationMs\x12\x14\n" +
	"\x05epoch\x18\x05 \x01(\x03R\x05epoch\"$\n" +
	"\fHeartbeatAck\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch2\x8c\x04\n" +
	"\x10WorkerManagement\x12Y\n" +
	"\x0eRegisterWorker\x12\".payflow.worker.v1.RegisterRequest\x1a#.payflow.worker.v1.RegisterResponse\x12V\n" +
	"\tHeartbeat\x12#.payflow.worker.v1.HeartbeatRequest\x1a$.payflow.worker.v1.HeartbeatResponse\x12P\n" +
	"\tPollTasks\x12\x1e.payflow.worker.v1.PollRequest\x1a!.payflow.worker.v1.TaskAssignment0\x01\x12K\n" +
	"\fReportResult\x12\x1d.payflow.worker.v1.TaskResult\x1a\x1c.payflow.worker.v1.ResultAck\x12L\n" +
	"\n" +
	"RevokeTask\x12 .payflow.worker.v1.RevokeRequest\x1a\x1c.payflow.worker.v1.RevokeAck\x12X\n" +
	"\x0fWorkerHeartbeat\x12 .payflow.worker.v1.HeartbeatPing\x1a\x1f.payflow.worker.v1.HeartbeatAck(\x010\x01B\x16Z\x14payflow/proto/workerb\x06proto3"

var (
	file_worker_proto_rawDescOnce sync.Once
	file_worker_proto_rawDescData []byte
)

func file_worker_proto_rawDescGZIP() []byte {
	file_worker_proto_rawDescOnce.Do(func() {
		file_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)))
	})
	return file_worker_proto_rawDescData
}

var file_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_worker_proto_goTypes = []any{
	(*RegisterRequest)(nil),   // 0: payflow.worker.v1.RegisterRequest
	(*RegisterResponse)(nil),  // 1: payflow.worker.v1.RegisterResponse
	(*HeartbeatRequest)(nil),  // 2: payflow.worker.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 3: payflow.worker.v1.HeartbeatResponse
	(*PollRequest)(nil),       // 4: payflow.worker.v1.PollRequest
	(*TaskAssignment)(nil),    // 5: payflow.worker.v1.TaskAssignment
	(*TaskResult)(nil),        // 6: payflow.worker.v1.TaskResult
	(*ResultAck)(nil),         // 7: payflow.worker.v1.ResultAck
	(*RevokeRequest)(nil),     // 8: payflow.worker.v1.RevokeRequest
	(*RevokeAck)(nil),         // 9: payflow.worker.v1.RevokeAck
	(*HeartbeatPing)(nil),     // 10: payflow.worker.v1.HeartbeatPing
	(*HeartbeatAck)(nil),      // 11: payflow.worker.v1.HeartbeatAck
}
var file_worker_proto_depIdxs = []int32{
	0,  // 0: payflow.worker.v1.WorkerManagement.RegisterWorker:input_type -> payflow.worker.v1.RegisterRequest
	2,  // 1: payflow.worker.v1.WorkerManagement.Heartbeat:input_type -> payflow.worker.v1.HeartbeatRequest
	4,  // 2: payflow.worker.v1.WorkerManagement.PollTasks:input_type -> payflow.worker.v1.PollRequest
	6,  // 3: payflow.worker.v1.WorkerManagement.ReportResult:input_type -> payflow.worker.v1.TaskResult
	8,  // 4: payflow.worker.v1.WorkerManagement.RevokeTask:input_type -> payflow.worker.v1.RevokeRequest
	10, // 5: payflow.worker.v1.WorkerManagement.WorkerHeartbeat:input_type -> payflow.worker.v1.HeartbeatPing
	1,  // 6: payflow.worker.v1.WorkerManagement.RegisterWorker:output_type -> payflow.worker.v1.RegisterResponse
	3,  // 7: payflow.worker.v1.WorkerManagement.Heartbeat:output_type -> payflow.worker.v1.HeartbeatResponse
	5,  // 8: payflow.worker.v1.WorkerManagement.PollTasks:output_type -> payflow.worker.v1.TaskAssignment
	7,  // 9: payflow.worker.v1.WorkerManagement.ReportResult:output_type -> payflow.worker.v1.ResultAck
	9,  // 10: payflow.worker.v1.WorkerManagement.RevokeTask:output_type -> payflow.worker.v1.RevokeAck
	11, // 11: payflow.worker.v1.WorkerManagement.WorkerHeartbeat:output_type -> payflow.worker.v1.HeartbeatAck
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_worker_proto_init() }
func file_worker_proto_init() {
	if File_worker_proto != nil {
		return
	}
	file_worker_proto_msgTypes[6].OneofWrappers = []any{
		(*TaskResult_Success)(nil),
		(*TaskResult_ErrorMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_proto_goTypes,
		DependencyIndexes: file_worker_proto_depIdxs,
		MessageInfos:      file_worker_proto_msgTypes,
	}.Build()
	File_worker_proto = out.File
	file_worker_proto_goTypes = nil
	file_worker_proto_depIdxs = nil
}
