// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.6
// source: proto/coordinator.proto

package coordinator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ElectionMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Any node receiving a lower-epoch message ignores it [cite: 96, 174]
	Epoch         int64  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	CandidateId   string `protobuf:"bytes,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElectionMessage) Reset() {
	*x = ElectionMessage{}
	mi := &file_proto_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElectionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElectionMessage) ProtoMessage() {}

func (x *ElectionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElectionMessage.ProtoReflect.Descriptor instead.
func (*ElectionMessage) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *ElectionMessage) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ElectionMessage) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

type ElectionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Epoch int64                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// The OK response in the Bully Algorithm
	Ok            bool `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElectionResponse) Reset() {
	*x = ElectionResponse{}
	mi := &file_proto_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElectionResponse) ProtoMessage() {}

func (x *ElectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElectionResponse.ProtoReflect.Descriptor instead.
func (*ElectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *ElectionResponse) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ElectionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type CoordinatorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Epoch int64                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// The COORDINATOR announcement
	LeaderId      string `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorMessage) Reset() {
	*x = CoordinatorMessage{}
	mi := &file_proto_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorMessage) ProtoMessage() {}

func (x *CoordinatorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorMessage.ProtoReflect.Descriptor instead.
func (*CoordinatorMessage) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *CoordinatorMessage) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *CoordinatorMessage) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_proto_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *AckResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_proto_coordinator_proto protoreflect.FileDescriptor

const file_proto_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x17proto/coordinator.proto\x12\x16payflow.coordinator.v1\"J\n" +
	"\x0fElectionMessage\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch\x12!\n" +
	"\fcandidate_id\x18\x02 \x01(\tR\vcandidateId\"8\n" +
	"\x10ElectionResponse\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"G\n" +
	"\x12CoordinatorMessage\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\"1\n" +
	"\vAckResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged2\xdb\x01\n" +
	"\x12CoordinatorCluster\x12]\n" +
	"\bElection\x12'.payflow.coordinator.v1.ElectionMessage\x1a(.payflow.coordinator.v1.ElectionResponse\x12f\n" +
	"\x13AnnounceCoordinator\x12*.payflow.coordinator.v1.CoordinatorMessage\x1a#.payflow.coordinator.v1.AckResponseB\x1bZ\x19payflow/proto/coordinatorb\x06proto3"

var (
	file_proto_coordinator_proto_rawDescOnce sync.Once
	file_proto_coordinator_proto_rawDescData []byte
)

func file_proto_coordinator_proto_rawDescGZIP() []byte {
	file_proto_coordinator_proto_rawDescOnce.Do(func() {
		file_proto_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_coordinator_proto_rawDesc), len(file_proto_coordinator_proto_rawDesc)))
	})
	return file_proto_coordinator_proto_rawDescData
}

var file_proto_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_coordinator_proto_goTypes = []any{
	(*ElectionMessage)(nil),    // 0: payflow.coordinator.v1.ElectionMessage
	(*ElectionResponse)(nil),   // 1: payflow.coordinator.v1.ElectionResponse
	(*CoordinatorMessage)(nil), // 2: payflow.coordinator.v1.CoordinatorMessage
	(*AckResponse)(nil),        // 3: payflow.coordinator.v1.AckResponse
}
var file_proto_coordinator_proto_depIdxs = []int32{
	0, // 0: payflow.coordinator.v1.CoordinatorCluster.Election:input_type -> payflow.coordinator.v1.ElectionMessage
	2, // 1: payflow.coordinator.v1.CoordinatorCluster.AnnounceCoordinator:input_type -> payflow.coordinator.v1.CoordinatorMessage
	1, // 2: payflow.coordinator.v1.CoordinatorCluster.Election:output_type -> payflow.coordinator.v1.ElectionResponse
	3, // 3: payflow.coordinator.v1.CoordinatorCluster.AnnounceCoordinator:output_type -> payflow.coordinator.v1.AckResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_coordinator_proto_init() }
func file_proto_coordinator_proto_init() {
	if File_proto_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_coordinator_proto_rawDesc), len(file_proto_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_coordinator_proto_goTypes,
		DependencyIndexes: file_proto_coordinator_proto_depIdxs,
		MessageInfos:      file_proto_coordinator_proto_msgTypes,
	}.Build()
	File_proto_coordinator_proto = out.File
	file_proto_coordinator_proto_goTypes = nil
	file_proto_coordinator_proto_depIdxs = nil
}