// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.6
// source: proto/coordinator.proto

package coordinator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoordinatorCluster_Election_FullMethodName            = "/payflow.coordinator.v1.CoordinatorCluster/Election"
	CoordinatorCluster_AnnounceCoordinator_FullMethodName = "/payflow.coordinator.v1.CoordinatorCluster/AnnounceCoordinator"
)

// CoordinatorClusterClient is the client API for CoordinatorCluster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoordinatorClusterClient interface {
	// Bully election messages
	Election(ctx context.Context, in *ElectionMessage, opts ...grpc.CallOption) (*ElectionResponse, error)
	AnnounceCoordinator(ctx context.Context, in *CoordinatorMessage, opts ...grpc.CallOption) (*AckResponse, error)
}

type coordinatorClusterClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinatorClusterClient(cc grpc.ClientConnInterface) CoordinatorClusterClient {
	return &coordinatorClusterClient{cc}
}

func (c *coordinatorClusterClient) Election(ctx context.Context, in *ElectionMessage, opts ...grpc.CallOption) (*ElectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ElectionResponse)
	err := c.cc.Invoke(ctx, CoordinatorCluster_Election_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClusterClient) AnnounceCoordinator(ctx context.Context, in *CoordinatorMessage, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, CoordinatorCluster_AnnounceCoordinator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinatorClusterServer is the server API for CoordinatorCluster service.
// All implementations must embed UnimplementedCoordinatorClusterServer
// for forward compatibility.
type CoordinatorClusterServer interface {
	// Bully election messages
	Election(context.Context, *ElectionMessage) (*ElectionResponse, error)
	AnnounceCoordinator(context.Context, *CoordinatorMessage) (*AckResponse, error)
	mustEmbedUnimplementedCoordinatorClusterServer()
}

// UnimplementedCoordinatorClusterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoordinatorClusterServer struct{}

func (UnimplementedCoordinatorClusterServer) Election(context.Context, *ElectionMessage) (*ElectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Election not implemented")
}
func (UnimplementedCoordinatorClusterServer) AnnounceCoordinator(context.Context, *CoordinatorMessage) (*AckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnnounceCoordinator not implemented")
}
func (UnimplementedCoordinatorClusterServer) mustEmbedUnimplementedCoordinatorClusterServer() {}
func (UnimplementedCoordinatorClusterServer) testEmbeddedByValue()                            {}

// UnsafeCoordinatorClusterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinatorClusterServer will
// result in compilation errors.
type UnsafeCoordinatorClusterServer interface {
	mustEmbedUnimplementedCoordinatorClusterServer()
}

func RegisterCoordinatorClusterServer(s grpc.ServiceRegistrar, srv CoordinatorClusterServer) {
	// If the following call panics, it indicates UnimplementedCoordinatorClusterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoordinatorCluster_ServiceDesc, srv)
}

func _CoordinatorCluster_Election_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElectionMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorClusterServer).Election(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorCluster_Election_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorClusterServer).Election(ctx, req.(*ElectionMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorCluster_AnnounceCoordinator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoordinatorMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorClusterServer).AnnounceCoordinator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorCluster_AnnounceCoordinator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorClusterServer).AnnounceCoordinator(ctx, req.(*CoordinatorMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// CoordinatorCluster_ServiceDesc is the grpc.ServiceDesc for CoordinatorCluster service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoordinatorCluster_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payflow.coordinator.v1.CoordinatorCluster",
	HandlerType: (*CoordinatorClusterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Election",
			Handler:    _CoordinatorCluster_Election_Handler,
		},
		{
			MethodName: "AnnounceCoordinator",
			Handler:    _CoordinatorCluster_AnnounceCoordinator_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/coordinator.proto",
}