// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/log/log.proto

package log

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         int64                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	TxnId         string                 `protobuf:"bytes,2,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_log_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_log_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_log_log_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *LogEntry) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *LogEntry) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *LogEntry) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type AppendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogIndex      int64                  `protobuf:"varint,1,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendResponse) Reset() {
	*x = AppendResponse{}
	mi := &file_proto_log_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendResponse) ProtoMessage() {}

func (x *AppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_log_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendResponse.ProtoReflect.Descriptor instead.
func (*AppendResponse) Descriptor() ([]byte, []int) {
	return file_proto_log_log_proto_rawDescGZIP(), []int{1}
}

func (x *AppendResponse) GetLogIndex() int64 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

func (x *AppendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntryRequest) Reset() {
	*x = GetEntryRequest{}
	mi := &file_proto_log_log_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntryRequest) ProtoMessage() {}

func (x *GetEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_log_log_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntryRequest.ProtoReflect.Descriptor instead.
func (*GetEntryRequest) Descriptor() ([]byte, []int) {
	return file_proto_log_log_proto_rawDescGZIP(), []int{2}
}

func (x *GetEntryRequest) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

type GetRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromIndex     int64                  `protobuf:"varint,1,opt,name=from_index,json=fromIndex,proto3" json:"from_index,omitempty"`
	ToIndex       int64                  `protobuf:"varint,2,opt,name=to_index,json=toIndex,proto3" json:"to_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRangeRequest) Reset() {
	*x = GetRangeRequest{}
	mi := &file_proto_log_log_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRangeRequest) ProtoMessage() {}

func (x *GetRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_log_log_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRangeRequest.ProtoReflect.Descriptor instead.
func (*GetRangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_log_log_proto_rawDescGZIP(), []int{3}
}

func (x *GetRangeRequest) GetFromIndex() int64 {
	if x != nil {
		return x.FromIndex
	}
	return 0
}

func (x *GetRangeRequest) GetToIndex() int64 {
	if x != nil {
		return x.ToIndex
	}
	return 0
}

type PendingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         int64                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingRequest) Reset() {
	*x = PendingRequest{}
	mi := &file_proto_log_log_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingRequest) ProtoMessage() {}

func (x *PendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_log_log_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingRequest.ProtoReflect.Descriptor instead.
func (*PendingRequest) Descriptor() ([]byte, []int) {
	return file_proto_log_log_proto_rawDescGZIP(), []int{4}
}

func (x *PendingRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type IdempotencyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IdempotencyRequest) Reset() {
	*x = IdempotencyRequest{}
	mi := &file_proto_log_log_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdempotencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdempotencyRequest) ProtoMessage() {}

func (x *IdempotencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_log_log_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdempotencyRequest.ProtoReflect.Descriptor instead.
func (*IdempotencyRequest) Descriptor() ([]byte, []int) {
	return file_proto_log_log_proto_rawDescGZIP(), []int{5}
}

func (x *IdempotencyRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type IdempotencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	TxnId         string                 `protobuf:"bytes,2,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdempotencyResponse) Reset() {
	*x = IdempotencyResponse{}
	mi := &file_proto_log_log_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdempotencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdempotencyResponse) ProtoMessage() {}

func (x *IdempotencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_log_log_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdempotencyResponse.ProtoReflect.Descriptor instead.
func (*IdempotencyResponse) Descriptor() ([]byte, []int) {
	return file_proto_log_log_proto_rawDescGZIP(), []int{6}
}

func (x *IdempotencyResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *IdempotencyResponse) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *IdempotencyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type WriteResultRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	TxnId          string                 `protobuf:"bytes,2,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	Success        bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WriteResultRequest) Reset() {
	*x = WriteResultRequest{}
	mi := &file_proto_log_log_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResultRequest) ProtoMessage() {}

func (x *WriteResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_log_log_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResultRequest.ProtoReflect.Descriptor instead.
func (*WriteResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_log_log_proto_rawDescGZIP(), []int{7}
}

func (x *WriteResultRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *WriteResultRequest) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *WriteResultRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type WriteResultAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResultAck) Reset() {
	*x = WriteResultAck{}
	mi := &file_proto_log_log_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResultAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResultAck) ProtoMessage() {}

func (x *WriteResultAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_log_log_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResultAck.ProtoReflect.Descriptor instead.
func (*WriteResultAck) Descriptor() ([]byte, []int) {
	return file_proto_log_log_proto_rawDescGZIP(), []int{8}
}

func (x *WriteResultAck) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type TxnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         int64                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	TxnId         string                 `protobuf:"bytes,2,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnRequest) Reset() {
	*x = TxnRequest{}
	mi := &file_proto_log_log_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnRequest) ProtoMessage() {}

func (x *TxnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_log_log_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnRequest.ProtoReflect.Descriptor instead.
func (*TxnRequest) Descriptor() ([]byte, []int) {
	return file_proto_log_log_proto_rawDescGZIP(), []int{9}
}

func (x *TxnRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *TxnRequest) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

type TxnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnResponse) Reset() {
	*x = TxnResponse{}
	mi := &file_proto_log_log_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnResponse) ProtoMessage() {}

func (x *TxnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_log_log_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnResponse.ProtoReflect.Descriptor instead.
func (*TxnResponse) Descriptor() ([]byte, []int) {
	return file_proto_log_log_proto_rawDescGZIP(), []int{10}
}

func (x *TxnResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_proto_log_log_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_log_log_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_proto_log_log_proto_rawDescGZIP(), []int{11}
}

type EpochRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         int64                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpochRequest) Reset() {
	*x = EpochRequest{}
	mi := &file_proto_log_log_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpochRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochRequest) ProtoMessage() {}

func (x *EpochRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_log_log_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochRequest.ProtoReflect.Descriptor instead.
func (*EpochRequest) Descriptor() ([]byte, []int) {
	return file_proto_log_log_proto_rawDescGZIP(), []int{12}
}

func (x *EpochRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type EpochResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         int64                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpochResponse) Reset() {
	*x = EpochResponse{}
	mi := &file_proto_log_log_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpochResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochResponse) ProtoMessage() {}

func (x *EpochResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_log_log_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochResponse.ProtoReflect.Descriptor instead.
func (*EpochResponse) Descriptor() ([]byte, []int) {
	return file_proto_log_log_proto_rawDescGZIP(), []int{13}
}

func (x *EpochResponse) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

var File_proto_log_log_proto protoreflect.FileDescriptor

const file_proto_log_log_proto_rawDesc = "" +
	"\n" +
	"\x13proto/log/log.proto\x12\x0epayflow.log.v1\"m\n" +
	"\bLogEntry\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch\x12\x15\n" +
	"\x06txn_id\x18\x02 \x01(\tR\x05txnId\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayloadJ\x04\b\x05\x10\v\"G\n" +
	"\x0eAppendResponse\x12\x1b\n" +
	"\tlog_index\x18\x01 \x01(\x03R\blogIndex\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"(\n" +
	"\x0fGetEntryRequest\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\"K\n" +
	"\x0fGetRangeRequest\x12\x1d\n" +
	"\n" +
	"from_index\x18\x01 \x01(\x03R\tfromIndex\x12\x19\n" +
	"\bto_index\x18\x02 \x01(\x03R\atoIndex\"&\n" +
	"\x0ePendingRequest\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch\"=\n" +
	"\x12IdempotencyRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\"^\n" +
	"\x13IdempotencyResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x15\n" +
	"\x06txn_id\x18\x02 \x01(\tR\x05txnId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"n\n" +
	"\x12WriteResultRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x15\n" +
	"\x06txn_id\x18\x02 \x01(\tR\x05txnId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"4\n" +
	"\x0eWriteResultAck\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"9\n" +
	"\n" +
	"TxnRequest\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch\x12\x15\n" +
	"\x06txn_id\x18\x02 \x01(\tR\x05txnId\"'\n" +
	"\vTxnResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x0e\n" +
	"\fEmptyRequest\"$\n" +
	"\fEpochRequest\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch\"%\n" +
	"\rEpochResponse\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch2\xde\x06\n" +
	"\x11PaymentLogService\x12G\n" +
	"\vAppendEntry\x12\x18.payflow.log.v1.LogEntry\x1a\x1e.payflow.log.v1.AppendResponse\x12E\n" +
	"\bGetEntry\x12\x1f.payflow.log.v1.GetEntryRequest\x1a\x18.payflow.log.v1.LogEntry\x12J\n" +
	"\vGetLogRange\x12\x1f.payflow.log.v1.GetRangeRequest\x1a\x18.payflow.log.v1.LogEntry0\x01\x12K\n" +
	"\rGetAllPending\x12\x1e.payflow.log.v1.PendingRequest\x1a\x18.payflow.log.v1.LogEntry0\x01\x12[\n" +
	"\x10CheckIdempotency\x12\".payflow.log.v1.IdempotencyRequest\x1a#.payflow.log.v1.IdempotencyResponse\x12Q\n" +
	"\vWriteResult\x12\".payflow.log.v1.WriteResultRequest\x1a\x1e.payflow.log.v1.WriteResultAck\x12H\n" +
	"\rHandlePrepare\x12\x1a.payflow.log.v1.TxnRequest\x1a\x1b.payflow.log.v1.TxnResponse\x12G\n" +
	"\fHandleCommit\x12\x1a.payflow.log.v1.TxnRequest\x1a\x1b.payflow.log.v1.TxnResponse\x12I\n" +
	"\x0eHandleRollback\x12\x1a.payflow.log.v1.TxnRequest\x1a\x1b.payflow.log.v1.TxnResponse\x12G\n" +
	"\bGetEpoch\x12\x1c.payflow.log.v1.EmptyRequest\x1a\x1d.payflow.log.v1.EpochResponse\x12I\n" +
	"\tSaveEpoch\x12\x1c.payflow.log.v1.EpochRequest\x1a\x1e.payflow.log.v1.WriteResultAckB\x13Z\x11payflow/proto/logb\x06proto3"

var (
	file_proto_log_log_proto_rawDescOnce sync.Once
	file_proto_log_log_proto_rawDescData []byte
)

func file_proto_log_log_proto_rawDescGZIP() []byte {
	file_proto_log_log_proto_rawDescOnce.Do(func() {
		file_proto_log_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_log_log_proto_rawDesc), len(file_proto_log_log_proto_rawDesc)))
	})
	return file_proto_log_log_proto_rawDescData
}

var file_proto_log_log_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_log_log_proto_goTypes = []any{
	(*LogEntry)(nil),            // 0: payflow.log.v1.LogEntry
	(*AppendResponse)(nil),      // 1: payflow.log.v1.AppendResponse
	(*GetEntryRequest)(nil),     // 2: payflow.log.v1.GetEntryRequest
	(*GetRangeRequest)(nil),     // 3: payflow.log.v1.GetRangeRequest
	(*PendingRequest)(nil),      // 4: payflow.log.v1.PendingRequest
	(*IdempotencyRequest)(nil),  // 5: payflow.log.v1.IdempotencyRequest
	(*IdempotencyResponse)(nil), // 6: payflow.log.v1.IdempotencyResponse
	(*WriteResultRequest)(nil),  // 7: payflow.log.v1.WriteResultRequest
	(*WriteResultAck)(nil),      // 8: payflow.log.v1.WriteResultAck
	(*TxnRequest)(nil),          // 9: payflow.log.v1.TxnRequest
	(*TxnResponse)(nil),         // 10: payflow.log.v1.TxnResponse
	(*EmptyRequest)(nil),        // 11: payflow.log.v1.EmptyRequest
	(*EpochRequest)(nil),        // 12: payflow.log.v1.EpochRequest
	(*EpochResponse)(nil),       // 13: payflow.log.v1.EpochResponse
}
var file_proto_log_log_proto_depIdxs = []int32{
	0,  // 0: payflow.log.v1.PaymentLogService.AppendEntry:input_type -> payflow.log.v1.LogEntry
	2,  // 1: payflow.log.v1.PaymentLogService.GetEntry:input_type -> payflow.log.v1.GetEntryRequest
	3,  // 2: payflow.log.v1.PaymentLogService.GetLogRange:input_type -> payflow.log.v1.GetRangeRequest
	4,  // 3: payflow.log.v1.PaymentLogService.GetAllPending:input_type -> payflow.log.v1.PendingRequest
	5,  // 4: payflow.log.v1.PaymentLogService.CheckIdempotency:input_type -> payflow.log.v1.IdempotencyRequest
	7,  // 5: payflow.log.v1.PaymentLogService.WriteResult:input_type -> payflow.log.v1.WriteResultRequest
	9,  // 6: payflow.log.v1.PaymentLogService.HandlePrepare:input_type -> payflow.log.v1.TxnRequest
	9,  // 7: payflow.log.v1.PaymentLogService.HandleCommit:input_type -> payflow.log.v1.TxnRequest
	9,  // 8: payflow.log.v1.PaymentLogService.HandleRollback:input_type -> payflow.log.v1.TxnRequest
	11, // 9: payflow.log.v1.PaymentLogService.GetEpoch:input_type -> payflow.log.v1.EmptyRequest
	12, // 10: payflow.log.v1.PaymentLogService.SaveEpoch:input_type -> payflow.log.v1.EpochRequest
	1,  // 11: payflow.log.v1.PaymentLogService.AppendEntry:output_type -> payflow.log.v1.AppendResponse
	0,  // 12: payflow.log.v1.PaymentLogService.GetEntry:output_type -> payflow.log.v1.LogEntry
	0,  // 13: payflow.log.v1.PaymentLogService.GetLogRange:output_type -> payflow.log.v1.LogEntry
	0,  // 14: payflow.log.v1.PaymentLogService.GetAllPending:output_type -> payflow.log.v1.LogEntry
	6,  // 15: payflow.log.v1.PaymentLogService.CheckIdempotency:output_type -> payflow.log.v1.IdempotencyResponse
	8,  // 16: payflow.log.v1.PaymentLogService.WriteResult:output_type -> payflow.log.v1.WriteResultAck
	10, // 17: payflow.log.v1.PaymentLogService.HandlePrepare:output_type -> payflow.log.v1.TxnResponse
	10, // 18: payflow.log.v1.PaymentLogService.HandleCommit:output_type -> payflow.log.v1.TxnResponse
	10, // 19: payflow.log.v1.PaymentLogService.HandleRollback:output_type -> payflow.log.v1.TxnResponse
	13, // 20: payflow.log.v1.PaymentLogService.GetEpoch:output_type -> payflow.log.v1.EpochResponse
	8,  // 21: payflow.log.v1.PaymentLogService.SaveEpoch:output_type -> payflow.log.v1.WriteResultAck
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_log_log_proto_init() }
func file_proto_log_log_proto_init() {
	if File_proto_log_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_log_log_proto_rawDesc), len(file_proto_log_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_log_log_proto_goTypes,
		DependencyIndexes: file_proto_log_log_proto_depIdxs,
		MessageInfos:      file_proto_log_log_proto_msgTypes,
	}.Build()
	File_proto_log_log_proto = out.File
	file_proto_log_log_proto_goTypes = nil
	file_proto_log_log_proto_depIdxs = nil
}
