// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.6
// source: proto/log.proto

package log

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentLogService_AppendEntry_FullMethodName      = "/payflow.log.v1.PaymentLogService/AppendEntry"
	PaymentLogService_GetEntry_FullMethodName         = "/payflow.log.v1.PaymentLogService/GetEntry"
	PaymentLogService_GetLogRange_FullMethodName      = "/payflow.log.v1.PaymentLogService/GetLogRange"
	PaymentLogService_GetAllPending_FullMethodName    = "/payflow.log.v1.PaymentLogService/GetAllPending"
	PaymentLogService_CheckIdempotency_FullMethodName = "/payflow.log.v1.PaymentLogService/CheckIdempotency"
	PaymentLogService_WriteResult_FullMethodName      = "/payflow.log.v1.PaymentLogService/WriteResult"
	PaymentLogService_HandlePrepare_FullMethodName    = "/payflow.log.v1.PaymentLogService/HandlePrepare"
	PaymentLogService_HandleCommit_FullMethodName     = "/payflow.log.v1.PaymentLogService/HandleCommit"
	PaymentLogService_HandleRollback_FullMethodName   = "/payflow.log.v1.PaymentLogService/HandleRollback"
)

// PaymentLogServiceClient is the client API for PaymentLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Dedicated gRPC service with BoltDB store
type PaymentLogServiceClient interface {
	// Append-only operations
	AppendEntry(ctx context.Context, in *LogEntry, opts ...grpc.CallOption) (*AppendResponse, error)
	GetEntry(ctx context.Context, in *GetEntryRequest, opts ...grpc.CallOption) (*LogEntry, error)
	GetLogRange(ctx context.Context, in *GetRangeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
	GetAllPending(ctx context.Context, in *PendingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
	// Idempotency deduplication
	CheckIdempotency(ctx context.Context, in *IdempotencyRequest, opts ...grpc.CallOption) (*IdempotencyResponse, error)
	WriteResult(ctx context.Context, in *WriteResultRequest, opts ...grpc.CallOption) (*WriteResultAck, error)
	// 2-Phase Commit for High-Value Payments
	HandlePrepare(ctx context.Context, in *TxnRequest, opts ...grpc.CallOption) (*TxnResponse, error)
	HandleCommit(ctx context.Context, in *TxnRequest, opts ...grpc.CallOption) (*TxnResponse, error)
	HandleRollback(ctx context.Context, in *TxnRequest, opts ...grpc.CallOption) (*TxnResponse, error)
}

type paymentLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentLogServiceClient(cc grpc.ClientConnInterface) PaymentLogServiceClient {
	return &paymentLogServiceClient{cc}
}

func (c *paymentLogServiceClient) AppendEntry(ctx context.Context, in *LogEntry, opts ...grpc.CallOption) (*AppendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendResponse)
	err := c.cc.Invoke(ctx, PaymentLogService_AppendEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentLogServiceClient) GetEntry(ctx context.Context, in *GetEntryRequest, opts ...grpc.CallOption) (*LogEntry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogEntry)
	err := c.cc.Invoke(ctx, PaymentLogService_GetEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentLogServiceClient) GetLogRange(ctx context.Context, in *GetRangeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PaymentLogService_ServiceDesc.Streams[0], PaymentLogService_GetLogRange_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRangeRequest, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PaymentLogService_GetLogRangeClient = grpc.ServerStreamingClient[LogEntry]

func (c *paymentLogServiceClient) GetAllPending(ctx context.Context, in *PendingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PaymentLogService_ServiceDesc.Streams[1], PaymentLogService_GetAllPending_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PendingRequest, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PaymentLogService_GetAllPendingClient = grpc.ServerStreamingClient[LogEntry]

func (c *paymentLogServiceClient) CheckIdempotency(ctx context.Context, in *IdempotencyRequest, opts ...grpc.CallOption) (*IdempotencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdempotencyResponse)
	err := c.cc.Invoke(ctx, PaymentLogService_CheckIdempotency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentLogServiceClient) WriteResult(ctx context.Context, in *WriteResultRequest, opts ...grpc.CallOption) (*WriteResultAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResultAck)
	err := c.cc.Invoke(ctx, PaymentLogService_WriteResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentLogServiceClient) HandlePrepare(ctx context.Context, in *TxnRequest, opts ...grpc.CallOption) (*TxnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TxnResponse)
	err := c.cc.Invoke(ctx, PaymentLogService_HandlePrepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentLogServiceClient) HandleCommit(ctx context.Context, in *TxnRequest, opts ...grpc.CallOption) (*TxnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TxnResponse)
	err := c.cc.Invoke(ctx, PaymentLogService_HandleCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentLogServiceClient) HandleRollback(ctx context.Context, in *TxnRequest, opts ...grpc.CallOption) (*TxnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TxnResponse)
	err := c.cc.Invoke(ctx, PaymentLogService_HandleRollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentLogServiceServer is the server API for PaymentLogService service.
// All implementations must embed UnimplementedPaymentLogServiceServer
// for forward compatibility.
//
// Dedicated gRPC service with BoltDB store
type PaymentLogServiceServer interface {
	// Append-only operations
	AppendEntry(context.Context, *LogEntry) (*AppendResponse, error)
	GetEntry(context.Context, *GetEntryRequest) (*LogEntry, error)
	GetLogRange(*GetRangeRequest, grpc.ServerStreamingServer[LogEntry]) error
	GetAllPending(*PendingRequest, grpc.ServerStreamingServer[LogEntry]) error
	// Idempotency deduplication
	CheckIdempotency(context.Context, *IdempotencyRequest) (*IdempotencyResponse, error)
	WriteResult(context.Context, *WriteResultRequest) (*WriteResultAck, error)
	// 2-Phase Commit for High-Value Payments
	HandlePrepare(context.Context, *TxnRequest) (*TxnResponse, error)
	HandleCommit(context.Context, *TxnRequest) (*TxnResponse, error)
	HandleRollback(context.Context, *TxnRequest) (*TxnResponse, error)
	mustEmbedUnimplementedPaymentLogServiceServer()
}

// UnimplementedPaymentLogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentLogServiceServer struct{}

func (UnimplementedPaymentLogServiceServer) AppendEntry(context.Context, *LogEntry) (*AppendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendEntry not implemented")
}
func (UnimplementedPaymentLogServiceServer) GetEntry(context.Context, *GetEntryRequest) (*LogEntry, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEntry not implemented")
}
func (UnimplementedPaymentLogServiceServer) GetLogRange(*GetRangeRequest, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Error(codes.Unimplemented, "method GetLogRange not implemented")
}
func (UnimplementedPaymentLogServiceServer) GetAllPending(*PendingRequest, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Error(codes.Unimplemented, "method GetAllPending not implemented")
}
func (UnimplementedPaymentLogServiceServer) CheckIdempotency(context.Context, *IdempotencyRequest) (*IdempotencyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckIdempotency not implemented")
}
func (UnimplementedPaymentLogServiceServer) WriteResult(context.Context, *WriteResultRequest) (*WriteResultAck, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteResult not implemented")
}
func (UnimplementedPaymentLogServiceServer) HandlePrepare(context.Context, *TxnRequest) (*TxnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandlePrepare not implemented")
}
func (UnimplementedPaymentLogServiceServer) HandleCommit(context.Context, *TxnRequest) (*TxnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleCommit not implemented")
}
func (UnimplementedPaymentLogServiceServer) HandleRollback(context.Context, *TxnRequest) (*TxnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleRollback not implemented")
}
func (UnimplementedPaymentLogServiceServer) mustEmbedUnimplementedPaymentLogServiceServer() {}
func (UnimplementedPaymentLogServiceServer) testEmbeddedByValue()                           {}

// UnsafePaymentLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentLogServiceServer will
// result in compilation errors.
type UnsafePaymentLogServiceServer interface {
	mustEmbedUnimplementedPaymentLogServiceServer()
}

func RegisterPaymentLogServiceServer(s grpc.ServiceRegistrar, srv PaymentLogServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentLogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentLogService_ServiceDesc, srv)
}

func _PaymentLogService_AppendEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentLogServiceServer).AppendEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentLogService_AppendEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentLogServiceServer).AppendEntry(ctx, req.(*LogEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentLogService_GetEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentLogServiceServer).GetEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentLogService_GetEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentLogServiceServer).GetEntry(ctx, req.(*GetEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentLogService_GetLogRange_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRangeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PaymentLogServiceServer).GetLogRange(m, &grpc.GenericServerStream[GetRangeRequest, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PaymentLogService_GetLogRangeServer = grpc.ServerStreamingServer[LogEntry]

func _PaymentLogService_GetAllPending_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PendingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PaymentLogServiceServer).GetAllPending(m, &grpc.GenericServerStream[PendingRequest, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PaymentLogService_GetAllPendingServer = grpc.ServerStreamingServer[LogEntry]

func _PaymentLogService_CheckIdempotency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdempotencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentLogServiceServer).CheckIdempotency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentLogService_CheckIdempotency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentLogServiceServer).CheckIdempotency(ctx, req.(*IdempotencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentLogService_WriteResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentLogServiceServer).WriteResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentLogService_WriteResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentLogServiceServer).WriteResult(ctx, req.(*WriteResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentLogService_HandlePrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentLogServiceServer).HandlePrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentLogService_HandlePrepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentLogServiceServer).HandlePrepare(ctx, req.(*TxnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentLogService_HandleCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentLogServiceServer).HandleCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentLogService_HandleCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentLogServiceServer).HandleCommit(ctx, req.(*TxnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentLogService_HandleRollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentLogServiceServer).HandleRollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentLogService_HandleRollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentLogServiceServer).HandleRollback(ctx, req.(*TxnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentLogService_ServiceDesc is the grpc.ServiceDesc for PaymentLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payflow.log.v1.PaymentLogService",
	HandlerType: (*PaymentLogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendEntry",
			Handler:    _PaymentLogService_AppendEntry_Handler,
		},
		{
			MethodName: "GetEntry",
			Handler:    _PaymentLogService_GetEntry_Handler,
		},
		{
			MethodName: "CheckIdempotency",
			Handler:    _PaymentLogService_CheckIdempotency_Handler,
		},
		{
			MethodName: "WriteResult",
			Handler:    _PaymentLogService_WriteResult_Handler,
		},
		{
			MethodName: "HandlePrepare",
			Handler:    _PaymentLogService_HandlePrepare_Handler,
		},
		{
			MethodName: "HandleCommit",
			Handler:    _PaymentLogService_HandleCommit_Handler,
		},
		{
			MethodName: "HandleRollback",
			Handler:    _PaymentLogService_HandleRollback_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetLogRange",
			Handler:       _PaymentLogService_GetLogRange_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAllPending",
			Handler:       _PaymentLogService_GetAllPending_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/log.proto",
}